### ISSUE TITLE
多言語化どぅする？

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/covid19#1]
## 改善詳細 / Details of Improvement
- 日本語以外の言語への対応どうする？

浜松だからポルトガル語への対応必要そう。

**Comment by poba1031** [comment]
・日本語のページができ次第、浜松市広聴広報課が国際課に依頼し翻訳する。
・すぐに翻訳する言語は、ポルトガル語と英語。
・その他の言語は改めて調整する。

**Comment by airsogi** [comment]
画面に表示されるテキストはほとんどが↓のように別ファイルに定義されています。参考までにー


https://github.com/code-for-hamamatsu/covid19/blob/dev-hamamatsu/assets/locales/ja.json

**Comment by airsogi** [comment]
翻訳ファイル、300行くらいありますが 全部翻訳する必要はないです。

### やり方

1. 言語切替して表示
2. 翻訳されていないラベルは日本語で表示されているので、各localeファイル(/assets/locales/~.json) から該当の箇所を探す
3. ある場合は翻訳、なければ新たに翻訳を追記する
