### ISSUE TITLE
右側カードの断捨離

### ISSUE THREAD

**Issue by NonbiriTarsan** [code-for-hamamatsu/covid19#10]
## 改善詳細 / Details of Improvement

code-for-hamamatsu/covid19の東京都のカードは以下の通り。
'/cards/details-of-confirmed-cases',                                検査陽性者の状況
'/cards/details-of-tested-cases',                                   検査実施状況
'/cards/number-of-confirmed-cases',                                 陽性患者数
'/cards/attributes-of-confirmed-cases',                             陽性患者の属性
'/cards/number-of-tested',                                          検査実施件数
'/cards/number-of-inspection-persons',                              検査実施人数
'/cards/number-of-reports-to-covid19-telephone-advisory-center',    新型コロナコールセンター相談件数
'/cards/number-of-reports-to-covid19-consultation-desk',            新型コロナ受診相談窓口相談件数
'/cards/predicted-number-of-toei-subway-passengers',                都営地下鉄の利用者数の推移
'/cards/agency',                                                    都庁来庁者数の推移
'/cards/shinjuku-visitors',                                         新宿区エリアの来訪者推移（参考値）
'/cards/chiyoda-visitors',                                          千代田区エリアの来訪者推移（参考値）
'/cards/shinjuku-st-heatmap',                                       新宿駅周辺の人口推移（参考値）
'/cards/tokyo-st-heatmap',                                          東京駅周辺の人口推移（参考値）
'/cards/tokyo-city-heatmap'                                         tokyo-city-heatmap

浜松市の出せるデータはどこまで。。
半分以上はいらないので、修正箇所を絞れると思います。
covid19-dev-hamamatsu/pages/index.vue から削るのと
covid19-dev-hamamatsu/nuxt.config.ts　　ここも。

**Comment by poba1031** [comment]
'/cards/number-of-reports-to-covid19-telephone-advisory-center', 浜松市帰国者・接触者相談センター相談件数
'/cards/number-of-inspection-persons', PCR検査実施人数
'/cards/number-of-confirmed-cases', 検査陽性患者数
'/cards/attributes-of-confirmed-cases', 検査陽性患者の属性
'/cards/details-of-confirmed-cases', 検査陽性者の状況

でお願いします。
