### ISSUE TITLE
一年点検

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/covid19#1007]
リリースから一年ほど経ったのでリファクタリングしたい。

## 現在感じている問題点

- 本番用ブランチ名(prod-hamamatsu)が一般的な名称ではない
- ローカル環境での起動に時間がかかる
- テストが無い

## 改善詳細 / Details of Improvement

- [x] 本番用ブランチ名を変更 ( `main` か `master` に)
- [ ] 不要なコンポーネント・使っていないnpmパッケージの除去
- [x] 不要なブランチの削除(6/9現在のブランチ数 66)
- [x] テストの追加
  - 最低限各ページが表示できることが確認できればよい

**Comment by euledge** [comment]
テストってE2Eテストですか？あまりフロントエンドテスト書いたことないのですがpuppeteerとか気になります。
https://developers.google.com/web/tools/puppeteer

**Comment by jacoyutorius** [comment]
そうですね、かんたんな確認程度でいいんですけどE2Eテスト入れたいなと。
pupetter良さそうですね、調べてみます〜

**Comment by euledge** [comment]
15か月以上前のブランチって本家からフォークしてきてた時のブランチですよね。
これって消しちゃってもいいと思うんですがどうでしょうか？
![image](https://user-images.githubusercontent.com/1209580/121766082-83acd700-cb8a-11eb-91d9-acc067e9b3ab.png)

**Comment by jacoyutorius** [comment]
確かに（今更ですが folkするとブランチも全部フォークされちゃうんですねぇ）
消しちゃいましょうかね

**Comment by euledge** [comment]
merged closed も消しておきました

**Comment by euledge** [comment]
残りは prod-hamamatsu dev-hamamatsu main のみです。*-hamamatsuどうするかはお任せします
