### ISSUE TITLE
グラフの年月表示がおかしい

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/covid19#1044]
## 起こっている問題 / The Problem
- グラフの横軸の年月表示部分が、`3 4 4` と4月ぶんが重複して表示されている

## スクリーンショット / Screenshot

![市内の最新感染動向___浜松市_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/662084/118144037-f2412c80-b446-11eb-9a89-54ecdb1435bc.jpg)

## 期待する見せ方・挙動 / Expected Behavior

- `3 4 5` と年月が正しく表示されるようにする

**Comment by ww2or3ww** [comment]
このバグは、私が作ったようです。
日付のフォーマットを MM/DD -> YYYY/MM/DD にした対応によるものです。 
issue : #846
pullreq : #847
![image](https://user-images.githubusercontent.com/6513552/118197150-51c02c00-b489-11eb-8ec0-b5f8dc36d07c.png)

日を表示すべきところ、月が表示されている。
年月を表示すべきところ、何も表示されていない。
![image](https://user-images.githubusercontent.com/6513552/118197191-6a304680-b489-11eb-9f1e-ad860802630e.png)

今晩あたり、バグ修正します！
