### ISSUE TITLE
トップ画面の最新のお知らせ自動更新を定期実行する

### ISSUE THREAD

**Issue by euledge** [code-for-hamamatsu/covid19#110]
## 改善詳細 / Details of Improvement
- 現在最新のお知らせはデプロイのタイミングで行っており、人手が必要なので遅れが生じている。これを定期的なサイトチェックにより自動で最新情報が表示できるようにしたい

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/1209580/78795074-81337800-79ef-11ea-852e-455ec46ece6c.png)

## 期待する見せ方・挙動 / Expected behavior
- GitHubActionのトリガーを時間実行にして開発サイトの自動デプロイ
- 本番サイトの自動デプロイについては議論ののち決めたい

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by euledge** [comment]
## 仕様概略（案）

- 市のHPが元データなので 9:00 - 21:00 の間で3h間隔での実行  
9:00、12:00、15:00、18:00、21:00 の5回

- 前回から更新があればdev-hamamatsuに対して自動commit&push
- 更新がなければcommitしない
- dev-hamamatsuで何回か実績あげてからprod-hamamatsuにも適用

**Comment by jacoyutorius** [comment]
> 更新がなければcommitしない

更新の有無ってGithubActions側から判定できるんでしょうか？？

**Comment by ww2or3ww** [comment]
@jacoyutorius 差分がなければ空振りするという認識でいますがどうでしょうか。

**Comment by euledge** [comment]
pythonスクリプトは毎回ファイル作ります。
ただ更新がない場合は、git commitすると
nothing to commit, working tree clean　でエラーになります。
エラーになっちゃうと、Action 自体がエラーになるので
```
     git commit -m "[BOT] Update news.json" || true
```
とやってShell 技でエラー回避してます。

git pushの場合は更新がない場合
Everything up-to-date　になりますが、こちらは正常終了になります。

git commitしないのではなくて、git commitしてもdev-hamamatuには影響しないっていうのが正確な意味ですね。

**Comment by euledge** [comment]
今見たら、浜松市のサイト２１時以降にも更新されてますね、時間見直したほうがいいかな
