### ISSUE TITLE
データ作成処理の共通化

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/covid19#127]
## 改善詳細 / Details of Improvement
- data.jsonとnews.jsonの作成を共通化したい
- 現在は、
   - data.jsonはdev-hamamatsuへのコミット
   - news.json はcron 
   - と作成タイミングに違いがある
- data.jsonを作成するLambdaは2or3氏のアカウントで運用されている。多少なりとも費用が発生しているはずなので、移管ないし費用の発生しない方法に変更したい

### 案1 API化

- data.json(既にLambdaで運用中)、news.jsonの作成処理をLambdaへ以降
- 各LambdaをAPI Gatewayに接続する
  - {APIGatewayのエンドポイント}/data
  - {APIGatewayのエンドポイント}/news
  - といったURLでjsonを取得できるようにし、GithubActionsで このAPIを叩いてJSONをDLし、コミットする

### 案2 GithubActionsで全てやるか

- data.jsonのデータ整形処理をGithubActionsで実行する

**Comment by euledge** [comment]
GitHub Actionsで完結できるならそちらのほうが良いのではないかと考えます。

**Comment by ww2or3ww** [comment]
@jacoyutorius @euledge すみません、コメント気付いてませんでした。

> data.jsonを作成するLambdaは2or3氏のアカウントで運用されている。多少なりとも費用が発生しているはずなので、移管ないし費用の発生しない方法に変更したい

Slackでも伝えましたが、費用発生するほど呼ばれていないので大丈夫です👌
市のクレジットが利用できるアカウントへの移管については、それもいいかもしれないですね。
Lambdaはzip食わせればいいだけですし、API Gatewayの設定についてはQiitaに書いておきました。
もちろん、アカウント貰えればワタシが構築するでも問題ないです😀

> GitHub Actionsで完結できるならそちらのほうが良い

csv2jsonをAPI経由で呼ぶのではなくて、dev-hamamatsu/toolの中に組み込んでしまう、ということですよね。

dataはオープンデータカタログから、newsは浜松市HPから、と
ソースの元が違いますので、無理に共通化する必要はないのかなぁと思いました。

csv2jsonのAPIは、静岡県オープンデータカタログを利用する他の市町村も利用できるような設計思想もありますので、newsを浜松市のHPからスクレイピングしてくるのはちょっと役割が違います。(オープンデータカタログでnews情報も管理されるなら話は変わってきますが。)

data生成とnew生成、2つの異なる役割を持つモジュールがあって、
それらを走らせる仕掛けは共通化してもいいと思います。
今2つに分かれているGitHub ActionsのWorkiflowを共通化するということですね。

**Comment by euledge** [comment]
> GitHub Actionsで完結できるならそちらのほうが良いのではないかと考えます。

私のこの意見は費用発生をなくすための方法としての意見でしたが、浜松市でAWSのクレジットが使用できるという条件がある場合はlambda使用する選択肢もあっていいと思います。
2or3のコメントにもあるように、オープンデータカタログからの生成に関しては他の市町村でも使用できるロジックであることはメリットと思う一方、他の市町村でもAWSを使用するかというのは微妙な気はします。

**Comment by ww2or3ww** [comment]
お気遣いありがとうございます😀

変な呼ばれ方しなければ、よっぽど費用は発生しないと思いますので、他の市町村もこのAPIを呼んでくれればいいんじゃないかなぁという気はしますね。ただそもそも他の市町村からのニーズがあるかどうかも不明なので今心配しても仕方ないですね。

ただAPIとしては、変な呼ばれ方した時に費用がぽーんと発生してしまわないような保険的な仕掛けはあったほうがいいかもしれないですね🤔この辺りは少し考えてみます。

**Comment by poba1031** [comment]
いま静岡市と話していますが（ただ広報課の職員でほぼITスキルゼロっぽいので、本当にゼロのゼロから伝えはじめています。こんなことやってる間にcode
for
に連絡すればいいのに、と思いますが、なんと「内製」にこだわっていますw）、まだ全然わからないですが、少なくとも静岡市には「静岡県のオープンデータカタログから2or3
の作ってくれたAPIを使った方がいいと思うよ」とは諭すつもりでいます。(^^)

2020年4月12日(日) 12:16 w2or3w <notifications@github.com>:

**Comment by ww2or3ww** [comment]
メモ
https://dev.classmethod.jp/articles/usage-plan-for-api-gateway/
この辺りで流量を制限できそう。キーごとに設定もできるようで良さそう。

**Comment by ww2or3ww** [comment]
@poba1031 API利用はまぁ置いておいて、オープンデータカタログに情報を上げるところは、早々にやってもらったほうが良い気はしますねー。

**Comment by poba1031** [comment]
ねー。

2020年4月12日(日) 12:50 w2or3w <notifications@github.com>:

**Comment by ww2or3ww** [comment]
> ただAPIとしては、変な呼ばれ方した時に費用がぽーんと発生してしまわないような保険的な仕掛けはあったほうがいいかもしれないですね🤔この辺りは少し考えてみます。

#132 にてdone

**Comment by jacoyutorius** [comment]
@ww2or3ww 表題とちょっと外れますが、data.jsonの作成はcronでやるようにしませんか？？

dev-hamamatsuへのコミットをフックにしていると、dev-hamamatsuに何も変更の無い日にdata.jsonが作成されないので 🤔

**Comment by ww2or3ww** [comment]
@jacoyutorius コミットをトリガーにしているのをスケジュール実行にする、ということですね。
はい、問題ありません。

.github/workflows/create_data_json.yml を、
.github/workflows/create_news_json.yml みたいにすればいいんですよね。

**Comment by ww2or3ww** [comment]
@jacoyutorius #142 にて下記対応をしています。
・APIキーによる認証
・APIキーをSecretsで管理
・cronによる定期実行

**Comment by jacoyutorius** [comment]
@ww2or3ww ありがとうございます！！
