### ISSUE TITLE
オープンデータ取得先が「ふじのくに」から「浜松市」へ変わったからUIのリンクも変更する

### ISSUE THREAD

**Issue by ww2or3ww** [code-for-hamamatsu/covid19#1310]
## 改善詳細 / Details of Improvement
「オープンデータを入手」の遷移先を以下に変更する。
陽性患者の属性：https://www.city.hamamatsu.shizuoka.jp/odpf/opendata/v1.html?x=221309_hamamatsu_covid19_patients
陽性患者数：https://www.city.hamamatsu.shizuoka.jp/odpf/opendata/v1.html?x=221309_hamamatsu_covid19_patients_summary
相談件数：https://www.city.hamamatsu.shizuoka.jp/odpf/opendata/v1.html?x=221309_hamamatsu_covid19_call_center

**Comment by poba1031** [comment]
ありがとうございます！
