### ISSUE TITLE
各種SNSリンクの表示

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/covid19#15]
## 改善詳細 / Details of Improvement
- フォークして最初のバージョンを作った際に消してしまったが、本家にはサイドバー下にLINE・Twitter・Facebookアカウントのリンクがある。これらを復活させる

## スクリーンショット / Screenshot
![都内の最新感染動向___東京都_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/662084/77907849-58abcf80-72c5-11ea-8266-ed8ba342682e.jpg)

**Comment by poba1031** [comment]
ちょうどこの4つでお願いします。

Facebookは、@hamamatsu.iira
Twitterは、@Hamamatsu_pr
LINEは、@hamamatsu

Gitのアカウントはここのでいいですよね？

**Comment by airsogi** [comment]
> Gitのアカウント

OKです!

**Comment by matsuihidetoshi** [comment]
~~@poba1031~~
~~LINEは、下記手順で友達追加用URLの生成が必要そうです🙇‍♂️~~
~~https://appllio.com/line-make-account-url-qrcode~~

不要でした😅
こちらで対応可能です！
https://line.me/R/ti/p/%40Hamamatsu
