### ISSUE TITLE
やさしい日本語 バージョンの作成

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/covid19#160]
## 改善詳細 / Details of Improvement
- やさしい日本語版への切り替えられるようにする

https://www.2020games.metro.tokyo.lg.jp/multilingual/references/easyjpn.html

**Comment by euledge** [comment]
本家のIssueには、やさしい日本語のルビ対応みたいなものもありますね
https://github.com/tokyo-metropolitan-gov/covid19/issues/3116
