### ISSUE TITLE
検査実施人数の注釈の変更

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/covid19#166]
## 改善詳細 / Details of Improvement

検査実施人数の1つ目と2つ目の注釈を以下のように修正する。

-（注）医療機関が保険適用で行った検査も含まれています。
-（注）入院患者の退院条件となる陰性確認のための検査は含まれていない。

**Comment by Naohiro2g** [comment]
日本語版だけでなく、英語版、ポルトガル語版、やさしい日本語版もですね。
日本語版の表記がマッチングのためのキーワードになるので、変更になった際は他の言語も手当が必要。

ですます統一
-（注）医療機関が保険適用で行った検査も含まれている。
-（注）入院患者の退院条件となる陰性確認のための検査は含まれていない。

そもそも、「医療機関が保険適用で行った検査も含まれている。」の意味が不明。「含まれていない」から「含まれている」に変わったが、保険適用／適用外すべてを含んでいるということか？

また、データの意味として、退院の際の確認検査は含まず、なので、のべ人数ではなく実人数を抽出しているということか？ データの意味合いを別の表現で書いたほうが良いかもしれない。


（参考）自動翻訳による仮訳（訳してみると何が言いたいか意味不明な感じが増す）

Note: This includes the tests that are covered by insurance.
Note: Negative tests to meet patient discharge criteria are not included.

Nota: Isto inclui os testes que são cobertos pelo seguro.
Nota: Isto não inclui os testes negativos para confirmar o critério de alta do paciente.

**Comment by jacoyutorius** [comment]
ちょっと日が経過してしまったので一旦closeとしますmm
