### ISSUE TITLE
Netlifyでデプロイに失敗している

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/covid19#1665]
## 起こっている問題 / The Problem
-11/16以降、Netlifyでのデプロイに失敗している

## スクリーンショット / Screenshot

<img width="909" alt="Site_overview___stopcovid19-hamamatsu" src="https://user-images.githubusercontent.com/662084/202778375-48743aff-e8b7-4d4c-9468-764217caac96.png">
<img width="955" alt="Deploy_details___stopcovid19-hamamatsu" src="https://user-images.githubusercontent.com/662084/202778460-19903adf-3cb5-4d32-86a0-ffb6706c397c.png">

### デプロイログ

```bash
6:16:15 PM: ---------------------------------------------------------------------
  UNSUPPORTED BUILD IMAGE

  The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.

  To enable builds for this site, select a later build image at the following link:
  https://app.netlify.com/sites/stopcovid19-hamamatsu/settings/deploys#build-image-selection

  For more details, visit the build migration guide:
  https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239
  ---------------------------------------------------------------------
```

## 期待する見せ方・挙動 / Expected Behavior
- デプロイに成功すること

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by jacoyutorius** [comment]
ここを変更。

<img width="1184" alt="Build___deploy___Site_settings" src="https://user-images.githubusercontent.com/662084/202779957-062ead0d-1881-4593-82e6-b774da09c0e3.png">

**Comment by jacoyutorius** [comment]
<img width="594" alt="Site_overview___stopcovid19-hamamatsu" src="https://user-images.githubusercontent.com/662084/202780058-9bdc1966-c243-4cea-ba00-ab5492ea4cf6.png">

**Comment by poba1031** [comment]
ありがとうございました🙇‍♂️
