### ISSUE TITLE
陽性テーブル(ConfirmedCasesAttributesCard)下部のGet Open Dataリンク先が東京都のままです

### ISSUE THREAD

**Issue by ww2or3ww** [code-for-hamamatsu/covid19#2]
## 起こっている問題 / The Problem
- 陽性患者の属性テーブル(ConfirmedCasesAttributesCard)下部のGet Open Dataリンク先が東京都でっす

## 期待する見せ方・挙動 / Expected Behavior
- 浜松市のデータソースへのリンクを。

**Comment by jacoyutorius** [comment]
ここは日別の感染者数の推移データなので、今公開されているオープンデータは合わないですね。。

検査状況と相談件数しか無い
https://opendata.pref.shizuoka.jp/dataset/search/?s%5Barea_id%5D=197

とりあえずリンクを非表示にしておこうかなと思います。

**Comment by jacoyutorius** [comment]
こういう形式がほしい

https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000068/resource/c2d997db-1450-43fa-8037-ebb11ec28d4c

**Comment by jacoyutorius** [comment]
別issueで直したのでクローズしますmm
