### ISSUE TITLE
最新のお知らせの更新

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/covid19#21]
## 改善詳細 / Details of Improvement
- 最新のお知らせ

## スクリーンショット / Screenshot
![市内の最新感染動向___浜松市_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/662084/77926401-0b3d5b80-72e1-11ea-80d3-7fa746550a95.jpg)

**Comment by euledge** [comment]
これはもう閉じてもよいかな？
