### ISSUE TITLE
PWAアイコンが東京のまま

### ISSUE THREAD

**Issue by ww2or3ww** [code-for-hamamatsu/covid19#28]
## 起こっている問題 / The Problem
- PWA(スマホのホームに追加するアレ)のアイコンが東京のままになってます。

## スクリーンショット / Screenshot
![ink (2)](https://user-images.githubusercontent.com/6513552/77965291-a6532700-731b-11ea-8c61-d1b5ebba59d8.png)

## 期待する見せ方・挙動 / Expected Behavior
- 浜松のアイコンが表示される。
- Android, iOS ともに
https://qiita.com/w2or3w/items/74a6e471501ee28ee9dd

**Comment by matsuihidetoshi** [comment]
なんだかダメみたいです。
参照先ファイルと参照方法がよくわからない…。

**Comment by suchi** [comment]
hamamatsuフォルダ下に浜松のリソースを置いていますが、static直下のicon.pngを直接置き換えてしまえば、このようにそれぞれ変更する必要がなさそうなので(おそらく #44 も解決)、東京リソースを残さないという選択肢もありますね。

**Comment by suchi** [comment]
お手数をおかけしてすみません。issue勘違いしていました。生成されるmanifest.jsonの画像もイチョウから入れ替わっていたのですが、スマホのときに出る画像は別のものなんですね。引き続き調査してみます。
