### ISSUE TITLE
グラフデータをSNSへシェアする挙動がTwitterとFBでおかしい（LINEは大丈夫な気がする）

### ISSUE THREAD

**Issue by poba1031** [code-for-hamamatsu/covid19#282]
## 起こっている問題 / The Problem
- グラフデータをSNSへシェアするボタンの挙動がTwitterとFBでおかしい気がする（LINEは大丈夫な気がする）
→タイトルに「東京」と表示されたり、シェアされるグラフデータが「東京」のような気がする。

## スクリーンショット / Screenshot
![screenshot-www facebook com-2020 05 18-17_36_38](https://user-images.githubusercontent.com/52411688/82192229-a68c9d80-992e-11ea-86e5-674e6c5e5347.png)
![screenshot-twitter com-2020 05 18-17_35_51](https://user-images.githubusercontent.com/52411688/82192233-a7bdca80-992e-11ea-8a3c-3e9089613a52.png)
![screenshot-stopcovid19 code4hamamatsu org-2020 05 18-17_34_28](https://user-images.githubusercontent.com/52411688/82192234-a8566100-992e-11ea-9fab-06cd251a4f8a.png)

**Comment by airsogi** [comment]
ご連絡ありがとうございます。

Slackでも回答しましたが、元々は東京版で実装されていた機能で、シェア時に表示される画像はリリースのたびにグラフの画像を生成して、そのリンクをシェアできるのでした。
（リリースのたびに画像が再作成されるので、常に最新のグラフがシェアできる）

浜松版では以下の理由により、この画像生成処理をオミットしていました。

- リリースを優先したため、早急に必要ではない機能は組み込まなかった
- 画像の生成に時間がかかる（静岡市版をメンテしている方からの情報。ヘッドレスchrome起動してpythonでスクショ撮ってるらしい）
- （使う人少ないだろうと思っていた）

SNSのシェアボタンを削除するほうほうで対応いたしますmm

**Comment by poba1031** [comment]
ありがとうございます。
水谷がどこかから指摘された模様です。
マストアイテムではないのでや（成仏）っちまっていただければと思います。

村越

2020年5月18日(月) 18:10 yuto ogi <notifications@github.com>:
