### ISSUE TITLE
オープンデータの整形メモ

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/covid19#30]
## 改善詳細 / Details of Improvement
- data.json のフォーマット
  - 全てのデータが data.json へ集約されていて、各グラフから必要なレコードのみ取り出して使っている

```
<confirmed-cases-card
      :title="$t('検査陽性者の状況')"
      :title-id="'details-of-confirmed-cases'"
      :date="Data.patients.date"
    >
```

## スクリーンショット / Screenshot
![data_json_—_covid19](https://user-images.githubusercontent.com/662084/77967528-40b56980-7320-11ea-8cee-692209f40784.jpg)

**Comment by ww2or3ww** [comment]
もう必要ないかなと思いますのでCloseします〜
