### ISSUE TITLE
印刷表示時のQRコードが本家のまま

### ISSUE THREAD

**Issue by airsogi** [code-for-hamamatsu/covid19#32]
## 起こっている問題 / The Problem
- 印刷表示時に右上に表示されるQRコードとURLがが本家のまま

## スクリーンショット / Screenshot
　
![新型コロナウイルス感染症にかかる相談窓口について___浜松市_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/49133851/77973727-0eac0380-7330-11ea-8788-db1a7dcaa7e6.png)

## 期待する見せ方・挙動 / Expected Behavior
- 記載されているURLは浜松市版のものに変える
- QRコードは消してもいいかも

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップ画面より右上の「印刷」をクリック

**Comment by poba1031** [comment]
修正したQRをアップしました

**Comment by poba1031** [comment]
差し替えデータをアップしました。

2020年3月31日(火) 9:16 yuto ogi <notifications@github.com>:
