### ISSUE TITLE
components/cards オープンデータの参照先リンクの修正

### ISSUE THREAD

**Issue by NonbiriTarsan** [code-for-hamamatsu/covid19#33]
## 改善詳細 / Details of Improvement
1:陽性患者の属性　　オープンデータデータなし
2:陽性患者数　　　　オープンデータデータなし
3:新型コロナ受診相談窓口相談件数　　　　　https://opendata.pref.shizuoka.jp/dataset/8108.html
4:新型コロナコールセンター相談件数　　　　3:と同じ？
5:検査実施人数　　　　                                    https://opendata.pref.shizuoka.jp/dataset/8109.html

components/cards/ConfirmedCasesAttributesCard.vue   陽性患者の属性
10:     -   :url="'https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000068'"

components/cards/ConfirmedCasesNumberCard.vue      陽性患者数
10:    -   :url="'https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000068'"

components/cards/ConsultationDeskReportsNumberCard.vue     新型コロナ受診相談窓口相談件数
10:    - :url="'https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000070'"
10:    + :url="'https://opendata.pref.shizuoka.jp/dataset/8108.html'"

components/cards/TelephoneAdvisoryReportsNumberCard.vue    新型コロナコールセンター相談件数
10:    -  :url="'https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000071'"

components/cards/InspectionPersonsNumberCard.vue　　　　　検査実施人数
10:    +  :url="'https://opendata.pref.shizuoka.jp/dataset/8109.html'"

**Comment by poba1031** [comment]
いま、水谷ももこが
1.2.4.5.と陽性者状況をオープンデータとして準備してます。

2020年3月31日(火) 9:47 NonbiriTarsan <notifications@github.com>:
