### ISSUE TITLE
新型コロナ受信相談窓口の電話番号が古い

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/covid19#340]
## 起こっている問題 / The Problem
- 新型コロナウイルス感染症にかかる相談窓口についてのページにある、新型コロナ受信相談窓口の電話番号が古い電話番号（053-453-6118）になっている

## スクリーンショット / Screenshot
 
![新型コロナウイルス感染症が心配なときに___浜松市_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/662084/83398591-9e5a5500-a43a-11ea-9721-f6ee1a5d2bb2.png)

## 期待する見せ方・挙動 / Expected Behavior
- フリーダイヤル（0120-368-567）に変更する

**Comment by poba1031** [comment]
すいません。ちゃんとチェックできてませんでした。申し訳ないです。m(__)m
村越

2020年6月1日(月) 19:04 jacoyutorius <notifications@github.com>:
