### ISSUE TITLE
Netlifyのビルド回数を減らしたい

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/covid19#342]
## 改善詳細 / Details of Improvement
- なんだかんだでNetlifyへの課金が発生しているので抑えたい
  - 先月は$21ほど
  - 一日にバッチが2回走り、そのたびにビルドが実行されるためトータルで無料枠のビルド時間(300min)を超えているかんじ？

## スクリーンショット / Screenshot

![Usage___insights___Builds](https://user-images.githubusercontent.com/662084/83422303-4afcfc80-a464-11ea-98b6-04fa770ceca8.jpg)

![General___Billing](https://user-images.githubusercontent.com/662084/83421552-408e3300-a463-11ea-9b58-3a23c517c74b.jpg)

**Comment by ww2or3ww** [comment]
@jacoyutorius @euledge 
1時間おきに実行されている data と news 更新処理を 1日1回(朝10時くらい？要相談)にする？
.github/workflows/create_data_news_json.yml
- cron:  '0 * * * *'
↓
- cron:  '0 10 * * *'

**Comment by jacoyutorius** [comment]
そうですね、一旦その設定にして様子見しようかなぁと。

実際にNetlifyのビルドが走るのは実際に差分が検出されたときなので、開発の落ち着いている時期は以下の画像のように一日2回（devとprod）だけなんですよね。

なので、そこまで回数削減できるかは怪しいんですが。。


ex) 5/31 のビルドを赤枠で囲んでいます
![Builds___jacoyutorius_s_team](https://user-images.githubusercontent.com/662084/83536882-d17e1080-a52e-11ea-9a55-45249eae231f.jpg)
（それかdevを停止するか。プルリク確認用環境作ってくれるからあまり必要無さそう・・？）

**Comment by euledge** [comment]
なんなら devはGithub pageにしちゃうとか
Github Pagesの制限は以下の通り
- 公開されたGitHub Pagesのサイトは1GB以上であってはなりません。
- GitHub Pages サイトには、月当たり 100GB のソフトな帯域幅制限があります。
- GitHub Pages サイトには、時間当たり 10 ビルドのソフトな制限があります

**Comment by ww2or3ww** [comment]
とりあえず毎時から毎日10時に変更しておきました。
https://github.com/code-for-hamamatsu/covid19/commit/f4ecf5c243e4112657b5110c7331da5bc24d1547

Dev環境の破棄についてはよろしくおねがいします😀 @jacoyutorius

**Comment by euledge** [comment]
データ更新のDevブランチへのマージはどうします?不要なら止めますけど？

**Comment by jacoyutorius** [comment]
↑コメントめっちゃ見落としてましたすみませんmm
dev環境削除したのでこのissueも閉じます~
