### ISSUE TITLE
フローに重複した連絡先がある

### ISSUE THREAD

**Issue by matsuihidetoshi** [code-for-hamamatsu/covid19#35]
## 改善詳細 / Details of Improvement
- `不安に思う方 -> 新型コロナコールセンター -> 専門的な助言が必要な場合 -> 新型コロナ受診相談窓口`となっているが、` 新型コロナコールセンター`と`新型コロナ受診相談窓口`が結局同じで、混乱を招きそうなので、`新型コロナコールセンター`の部分は削除で良さげ

## スクリーンショット / Screenshot
<img width="678" alt="1893ebbc27f9c4007e1a95e691a28df4" src="https://user-images.githubusercontent.com/38583473/77980831-5720ec80-7343-11ea-81ec-2ebe2c1c5567.png">

## 期待する見せ方・挙動 / Expected behavior
- PC、SP共に、` 新型コロナコールセンター`は削除でいいのでは
- PCの方はカードごと消して、その分左側の`不安に思う方`のカードを広げてはどうか

## 動作環境・ブラウザ / Environment
- macOS
- Chrome

**Comment by poba1031** [comment]
それで良さげです

2020年3月31日(火) 11:36 matsuihidetoshi <notifications@github.com>:
