### ISSUE TITLE
「新型コロナウイルス感染症が心配なときに」のフローの修正

### ISSUE THREAD

**Issue by poba1031** [code-for-hamamatsu/covid19#413]
フローが古いままだったので、修正してもらえるとうれしいです。

https://jaws-ug-hamamatsu.slack.com/archives/C0111LQQP71/p1593428408219500

参考（厚労省新基準）
ーーーーーーーーー
次の症状がある方は下記を目安に「帰国者・接触者相談センター」にご相談ください。
○　少なくとも以下のいずれかに該当する場合には、すぐに御相談ください。（これらに該当しない場合の相談も可能です。）
☆　息苦しさ（呼吸困難）、強いだるさ（倦怠感）、高熱等の強い症状のいずれかがある場合
☆　重症化しやすい方（※）で、発熱や咳などの比較的軽い風邪の症状がある場合
（※）高齢者、糖尿病、心不全、呼吸器疾患（COPD等）等の基礎疾患がある方や透析を受けている方、免疫抑制剤や抗がん剤等を用いている方
☆　上記以外の方で発熱や咳など比較的軽い風邪の症状が続く場合
（症状が４日以上続く場合は必ずご相談ください。症状には個人差がありますので、強い症状と思う場合にはすぐに相談してください。解熱剤などを飲み続けなければならない方も同様です。）
 
○　相談は、帰国者・接触者相談センター（地域により名称が異なることがあります。）の他、地域によっては、医師会や診療所等で相談を受け付けている場合もあるので、ご活用ください。
 
（妊婦の方へ）
　妊婦の方については、念のため、重症化しやすい方と同様に、早めに帰国者・接触者相談センター等に御相談ください。
 
（お子様をお持ちの方へ）
　小児については、小児科医による診察が望ましく、帰国者・接触者相談センターやかかりつけ小児医療機関に電話などで御相談ください。
 
※なお、この目安は、国民のみなさまが、相談・受診する目安です。これまで通り、検査については医師が個別に判断します。

 【医療機関にかかるときのお願い】
○　複数の医療機関を受診することにより感染を拡大した例がありますので、複数の医療機関を受診することはお控えください。
○　医療機関を受診する際にはマスクを着用するほか、手洗いや咳エチケット（咳やくしゃみをする際に、マスクやティッシュ、ハンカチ、袖・肘の内側などを使って、口や鼻をおさえる）の徹底をお願いします。
----------

参考（本家）
https://stopcovid19.metro.tokyo.lg.jp/flow/

**Comment by ww2or3ww** [comment]
#416 
ひとまずワーディングの変更や削除のみ対応。
レイアウトに影響する変更は見送ってます。

追加したワーディングは以下。
"感染の予防": "Prevention infection",
"感染の予防": "感染(かんせん)の予防(よぼう)",
(※ポルトガルも英語を表示してる)

**Comment by jacoyutorius** [comment]
対応ありがとうございました！
