### ISSUE TITLE
OGPの画像上にあるアドレス横にある小さなアイコンが東京のまま

### ISSUE THREAD

**Issue by ww2or3ww** [code-for-hamamatsu/covid19#44]
## 起こっている問題 / The Problem
- OGP(SNSとかにシェアしたときにペラっと表示されるアレ)の画像はさしかわりましたが、その上の説明の更にその上にあるアドレスの横にあるちっさなアイコンが東京のままです。

## スクリーンショット / Screenshot
![ink (3)](https://user-images.githubusercontent.com/6513552/78033919-042a5200-73a2-11ea-91b5-b6c65cb4ea31.png)

## 期待する見せ方・挙動 / Expected Behavior
- 浜松のアイコンにする

**Comment by euledge** [comment]
やっぱり一瞬イチョウが表示されて、浜松市章になりますね
他の県のサイトはどうしてるにかと思ってみてみましたが、イチョウは表示されずコンパスのアイコン（safariのアイコンみたいなモノクロのやつ）が表示されてから各県のアイコンに変わる動きでした。
おそらくイチョウアイコンは消してしまっている（上書き）のでは

北海道の関連issue
https://github.com/codeforsapporo/covid19/issues/53

**Comment by ww2or3ww** [comment]
修正されていることを確認しました〜
どのPLが解決したんだろう、、。(#53 かな？)
