### ISSUE TITLE
中国語版の作成

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/covid19#454]
## 改善詳細 / Details of Improvement
- `/assets/locales/` 配下に中国語用の翻訳ファイル(json)を作る
- nuxt.config.ts の`locales` に中国語の言語コード`zh`追加

```
  generate: {
    fallback: true,
    routes() {
      const locales = ['ja', 'ja-basic', 'en', 'pt-br']
```

- `nuxt-i18n.config.ts`にも追記

## 期待する見せ方・挙動 / Expected behavior
- 言語選択で中国語に切り替えることがでること

## 翻訳ファイル

[【中国語】コロナ対策サイト_28408_marked.docx](https://github.com/code-for-hamamatsu/covid19/files/4931280/_28408_marked.docx)

**Comment by ww2or3ww** [comment]
#460 プルリクにも書きましたが、何箇所か足りてないワードがありますので、
表示内容の確認とあわせて追加翻訳を検討ください〜

![ink (36)](https://user-images.githubusercontent.com/6513552/87843774-2369d280-c8f2-11ea-8d7d-45702eb6d9a2.png)

**Comment by jacoyutorius** [comment]
対応ありがとうございました！
