### ISSUE TITLE
ポルトガル語を有効にして言語選択を切り替えるとトップページのグラフが表示されない

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/covid19#48]
## 改善詳細 / Details of Improvement
- 言語選択セレクトボックスでポルトガル語を選択できるようにする
- 日付フォーマットの変換でエラーになっている様子
  - chartjs側でも同じエラーが発生しているようなので最悪言語によって日付フォーマットを切り替えないといけないかもしれない

## スクリーンショット / Screenshot
![浜松市_新型コロナウイルス感染症対策サイト___浜松市_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/662084/78052729-79a21c80-73ba-11ea-9d76-7476e9e569b3.jpg)

## 参考

- https://qiita.com/Ancient_Scapes/items/f5fbe7314c6f71a263da#%E3%81%A8%E3%82%8A%E3%81%82%E3%81%88%E3%81%9A%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E5%86%85%E3%81%A7moment%E3%82%92%E5%AF%BE%E8%B1%A1%E3%81%ABgrep%E3%81%97%E7%BD%AE%E6%8F%9B%E3%81%97%E3%81%A6%E3%81%84%E3%81%8F

**Comment by jacoyutorius** [comment]
data.jsonに記載されている日付のフォーマットが"/"区切りなのが原因かも・・？

**Comment by ksk1015** [comment]
ポルトガル語の追加は自分は問題なくできたので、もしかしてうまくいかなかったのは、 nuxt.config.ts のgenerateプロパティにポルトガル語を追加しなかったからではないでしょうか。

https://github.com/code-for-hamamatsu/covid19/blob/e54f00eaa9563fa54dfdf11d9cff4f0db5716e42/nuxt.config.ts#L163

**Comment by jacoyutorius** [comment]
そこのプロパティには追加したんですけど駄目ですね、、、
もしお手間でなければ変更箇所おしえていただけますか? mm  (プルリク、スクショ、なんでもいいです)

**Comment by ksk1015** [comment]
ではプルリクします
