### ISSUE TITLE
最新のお知らせが縦に長い

### ISSUE THREAD

**Issue by ww2or3ww** [code-for-hamamatsu/covid19#488]
## 改善詳細 / Details of Improvement
- 最新のお知らせが縦に長い

## スクリーンショット / Screenshot
![screenshot_20200724-185655](https://user-images.githubusercontent.com/6513552/88454216-e630b200-cea8-11ea-9c79-75187b2ae798.png)

## 期待する見せ方・挙動 / Expected behavior
- スクロール付きの領域にする？

**Comment by jacoyutorius** [comment]
いいですね！対応ありがとうございました〜 👍
