### ISSUE TITLE
「はままつしLINEコロナ身守りシステム」や「COCOA」へのリンクを載せる

### ISSUE THREAD

**Issue by ww2or3ww** [code-for-hamamatsu/covid19#494]
## 改善詳細 / Details of Improvement
- 「はままつしLINEコロナ身守りシステム」や「COCOA」へのリンクを載せる
- 「民間支援情報ナビ For 静岡県版」は更新されていないようなので外す

## 期待する見せ方・挙動 / Expected behavior
- 左側のナビゲーションでいいかな？

**Comment by euledge** [comment]
LGTM
