### ISSUE TITLE
READMEを浜松用に直す

### ISSUE THREAD

**Issue by airsogi** [code-for-hamamatsu/covid19#50]
## 改善詳細 / Details of Improvement

- タイトル・画像の差し替え
- 不要そうな項目の削除
- contribute方法

等の見直し

**Comment by euledge** [comment]
さしあたって変えた方が良い場所としては
- README 内のリンクでまだtokyo.netlify.comになっているものをhamamatsu.netlify.comに変更  
もしかしてstaging環境はないですか？
- ブランチルールの開発ブランチ名をdevelopからdev-hamamatsuにする

位かと思いますがどうでしょうか？
上記であっていればやりますよ。

今どんなフローでデプロイしているのか教えてもらえるともう少しできると思います。
#66 にも関係していてGithubActionで自動化するなら流れの理解をしておきたいです。

**Comment by jacoyutorius** [comment]
ありがとうございます！
今は2つの環境にデプロイしていて、dev-hamamatsuをデプロイしたものがstaging兼ねてますね。

| 目的 | ブランチ | 確認URL | 備考 |
| ---- | -------- | ---- | ---- |
| 開発 | dev-hamamatsu | https://dev-stopcovid19-hamamatsu.netlify.com/ | base branch。基本はこちらに Pull Requestを送ってください |
| 本番 | prod-hamamatsu | https://stopcovid19-hamamatsu.netlify.com/ | 管理者以外の Pull Request は禁止です |

**Comment by euledge** [comment]
とりあえずマージしちゃったんですね。
本当は本番環境への反映もやっておきたかったけど、まあコントリビューターには関係ないからいいかw

**Comment by euledge** [comment]
@jacoyutorius 
一つ聞きたいんですが、今の運用でnetlifyへのデプロイってどうしているんでしょうか？
NetlifyとGitHubの連携で自動化できるようなこと書いてあるサイトがあるんですが
それを見ると特定のブランチを紐づけておけばGitHub pageへのpushだけで行けると思うんだけど
どうでしょうか？

https://tech.moyashidaisuke.com/entry/covid19-netlify

**Comment by jacoyutorius** [comment]
今は、私のNetlifyアカウントでデプロイしています。
dev-hamamatsuとprod-hamamatsuにpushされると自動的にデプロイされますね〜

Netlifyのデプロイ環境も解法したいんですけどやり方よくわからない。。

**Comment by jacoyutorius** [comment]
プルリク作るとNetlifyが自動で検証用の環境作ってくれます。
以下のリンクから見れます◎

![WIP_最新のお知らせを自動で生成する_by_euledge_·_Pull_Request__78_·_code-for-hamamatsu_covid19](https://user-images.githubusercontent.com/662084/78498911-79be6580-7788-11ea-9eeb-68efdc8c80c8.jpg)

**Comment by jacoyutorius** [comment]
dev-hamamatsuからprod-hamamatsuへの反映は僕が任意のタイミングでプルリク作ってやってる感じですね、この辺も自動化すべきなのでしょうけど。。

**Comment by euledge** [comment]
dev|prod-hamamatsuとNetlifyがリンクされているんですね。了解です。
それだとすると最新のお知らせのJsonいれるやつは、dev-hamamatsuからprod-hamamatsuにPRしたときに動かせばよさげです。

本家のサイトではデータ更新用のブランチが切ってあってそこにデータをコミットするとデータのみstaging,productionに反映するみたいです。
![image](https://user-images.githubusercontent.com/1209580/78499477-e8e98900-778b-11ea-8785-3556b0d0acd0.png)
