### ISSUE TITLE
浜松市ロゴの解像度が低い

### ISSUE THREAD

**Issue by airsogi** [code-for-hamamatsu/covid19#6]
## 改善詳細 / Details of Improvement
- もらった画像を透過pngに加工したためか、画像が荒くなっている
  - 本家と同じようにsvgに差し替えたほうが良さそう？

## スクリーンショット / Screenshot
![都内の最新感染動向___東京都_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/49133851/77865315-9cbcb700-7268-11ea-960b-77328f41e6c8.png)

**Comment by poba1031** [comment]
1.2MBモノを用意しました。

**Comment by airsogi** [comment]
イラレ形式からsvgで書き出せますよね、確か。
ここのロゴはsvgがいいなー 😄 

拡大するとギザつく
![新型コロナウイルス感染症について／浜松市](https://user-images.githubusercontent.com/49133851/77984490-aa4b6d00-734c-11ea-980e-2dafc5959831.png)


本家
![都内の最新感染動向___東京都_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/49133851/77984534-c3541e00-734c-11ea-8c97-504c3aeb8c34.png)
