### ISSUE TITLE
本家の「このサイトから派生したサイト」に記載してもらう

### ISSUE THREAD

**Issue by airsogi** [code-for-hamamatsu/covid19#67]
## 改善詳細 / Details of Improvement
-プルリク出す

**Comment by chihiroyn** [comment]
出してみまーす。

**Comment by chihiroyn** [comment]
出しときまーす

**Comment by chihiroyn** [comment]
本家にPR出しときましたー
https://github.com/tokyo-metropolitan-gov/covid19/pull/2873

**Comment by airsogi** [comment]
おっ、ありがとうございます！
mergeされましたね。プルリクのコメントにある、「StopCovid19JP地域展開」のGoogleスプレッドシートには私の方で追記しておきました。

**Comment by chihiroyn** [comment]
どうもありがとうございました！
