### ISSUE TITLE
nuxt-i18n.config.ts nuxt.config.ts　で言語を絞る

### ISSUE THREAD

**Issue by NonbiriTarsan** [code-for-hamamatsu/covid19#8]
## 改善詳細 / Details of Improvement
nuxt-i18n.config.ts

      name: '日本語',
      name: 'English',
      name: '繁體中文',
      name: '한국어',
      name: 'やさしい にほんご',

とあるけど日本語とポルトガル語に絞る？
こんなに対応できない。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/4452326/77869329-0f359300-7279-11ea-9b88-dae0ab0105a2.png)

**Comment by airsogi** [comment]
https://github.com/code-for-hamamatsu/covid19/issues/1#issuecomment-605807934

- 日本語
- 英語
- ポルトガル語

を用意する。
ポルトガル語はとりあえず日本語ファイルのコピーで。

**Comment by poba1031** [comment]
了解。
アップ後すぐに国際課に翻訳を手配します。

2020年3月31日(火) 12:53 yuto ogi <notifications@github.com>:

**Comment by airsogi** [comment]
あざます、本日中に言語切替のとこ直します〜

**Comment by jacoyutorius** [comment]
ポルトガル語は `pt-BR`(ブラジルポルトガル語) でいいのかな？？

**Comment by jacoyutorius** [comment]
途中まで書かれた翻訳ファイルあった

https://github.com/code-for-hamamatsu/covid19/blob/dev-hamamatsu/assets/locales/pt_BR.json

**Comment by poba1031** [comment]
OKです。

2020年3月31日(火) 22:57 jacoyutorius <notifications@github.com>:
