### ISSUE TITLE
英語版の「帰国者・接触者相談センターについて」ほか一部が英訳されていない

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/covid19#90]
## スクリーンショット / Screenshot
![If_you_feel_concerned_about_COVID-19___浜松市_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/662084/78544701-8351d700-7835-11ea-810d-40fd868988e4.png)

**Comment by jacoyutorius** [comment]
@poba1031 お願いシャッス〜

**Comment by Naohiro2g** [comment]
英訳をお手伝いしようと思いますが、進捗はどうでしょうか？
 feature/#90-#translation_en ブランチを切って、dev-hamamatsuブランチにプルリクを送ればよいですよね？

**Comment by Naohiro2g** [comment]
なお、assets/locales/en.json だけでなく、/locales/に吸収されていない、以下の問題点については別issueを立てますか？ あるいは、「英訳」ということでこのissueでまとめるか。
 - 左カラムのリンク先3つは直接の英語版が存在しないので、リンク先自体を考える／削減／追加の必要あり。
 - トップページ／最新のお知らせ／What's Newの中身の英訳（場合によってはリンク先）をどうするか。

浜松市ホームページへのリンクの場合、暫定的にはサイト構成上、「Foreign Language」へぶっ飛ばしになると思います。一部、より良いリンク先があるような場合も出てくると思いますが、URL変更などへの対応が大変になりそう。https://www.city.hamamatsu.shizuoka.jp/foreign/index.html

**Comment by airsogi** [comment]
確認ありがとうございます〜このissueでは以下の対応だけすれば良いかなと思っています。

> 左カラムのリンク先3つは直接の英語版が存在しないので、リンク先自体を考える／削減／追加の必要あり。

とりあえずリンク先はそのままでお願いします。

> トップページ／最新のお知らせ／What's Newの中身の英訳（場合によってはリンク先）をどうするか

こちらも翻訳不要です。

まずはラベルだけ翻訳すればいいやという考えでいます。
理由としてはおっしゃるとおりで、各言語に対応するページが存在しないことと、リンクまで変えようとするとプログラムでの対応が必要になるためですね。

各言語対応するには浜松市側の協力（英語・ポルトガル語向けのページ用意やお知らせの用意）も必要になるので、やるとすれば足並み揃えてやったほうがいいかなと。

**Comment by poba1031** [comment]
もう一度水谷にプッシュします。

2020年4月17日(金) 16:43 Naohiro Tsuji <notifications@github.com>:

**Comment by Naohiro2g** [comment]
本件を解決する PR #147 が本番環境まで反映されたので、まとめておきます。

多言語対応では、
英語版は PR #147 により問題ない状態、ポルトガル語版はissue #88 、やさしいにほんごについて  issue #160 が残っています。

なお、東京版はTransifexによる翻訳体制に移行しています。assets/locales/ 以下のjsonファイルでの運用をやめていくのかと思ったら、継続していました。また、こんなissueが立っていました。
https://github.com/tokyo-metropolitan-gov/covid19/issues/3435
ポルトガル語版も58％できている。行政の確認が遅れているとのこと。

浜松版では、まず、日本語、英語、ポルトガル語、やさしいにほんごを整備して体制を整える方針。
https://www.transifex.com/ はオープンソースプロジェクトなら無料で使えるので、市との協力体制が整ってきたら導入を検討。transifex-github連携でPRまで行けるため、技術系でない人も協力しやすくなる可能性あり。

**Comment by airsogi** [comment]
対応 & まとめありがとうございます！
